name: Newman Run

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: postman/collections/NOVA Security Tests_e438b0c3-97c2-46fa-b650-f154724258c8.json
          environment: postman/environments/nova-security-tests.json


          
